version: 2
updates:
  # Root workspace dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "handrades"
    reviewers:
      - "handrades"
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "jest*"
          - "typescript*"
          - "prettier*"
          - "ts-*"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"
      
  # API app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "handrades"
    reviewers:
      - "handrades"
    open-pull-requests-limit: 5
    groups:
      express-ecosystem:
        patterns:
          - "express*"
          - "cors"
          - "helmet"
          - "compression"
        update-types:
          - "minor"
          - "patch"
      database-ecosystem:
        patterns:
          - "typeorm*"
          - "pg*"
          - "@types/pg*"
          - "reflect-metadata"
        update-types:
          - "minor"
          - "patch"
      security-ecosystem:
        patterns:
          - "bcrypt*"
          - "uuid*"
          - "jsonwebtoken*"
        update-types:
          - "patch"
      testing-dependencies:
        patterns:
          - "jest*"
          - "supertest*"
          - "@types/jest*"
          - "@types/supertest*"
          - "ts-jest*"
        update-types:
          - "minor"
          - "patch"
          
  # Web app dependencies  
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "handrades"
    reviewers:
      - "handrades"
    open-pull-requests-limit: 5
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      mui-ecosystem:
        patterns:
          - "@mui/*"
          - "@emotion/*"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
        update-types:
          - "minor"
          - "patch"
      testing-dependencies:
        patterns:
          - "jest*"
          - "@testing-library/*"
          - "@types/jest*"
          - "jest-environment-jsdom*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "handrades"
    reviewers:
      - "handrades"
    open-pull-requests-limit: 3