# pnpm workspace configuration for Industrial Inventory Multi-App Framework
packages:
  - "apps/*"
  - "packages/*"

# Performance optimizations for air-gapped environments
prefer-workspace-packages: true
link-workspace-packages: true
save-workspace-protocol: rolling

# Hoisting configuration for better dependency management
hoist-pattern:
  - "*"

# Registry configuration for air-gapped environments
registry: "https://registry.npmjs.org/"

# Package resolution preferences
resolution-mode: "highest"