---
name: Lint

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  lint:
    name: Run Linting Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Setup Python for yamllint
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Node.js linting tools
        run: |
          npm install -g markdownlint-cli@latest
          npm install -g jsonlint@latest

      - name: Install Python linting tools
        run: |
          pip install yamllint

      - name: Lint Markdown files
        run: |
          echo "Checking Markdown files..."
          if find . -name "*.md" -not -path "./node_modules/*" \
                     -not -path "./.bmad-core/*" | head -1 | grep -q .; then
            markdownlint "**/*.md" \
                         --ignore node_modules --ignore .bmad-core \
                         --config config/.markdownlint.json
            echo "✓ Markdown linting passed"
          else
            echo "No markdown files found to lint"
          fi

      - name: Lint JSON files
        run: |
          echo "Checking JSON files..."
          json_files=$(find . -name "*.json" -not -path "./node_modules/*" \
                                 -not -path "./.bmad-core/*")
          if [ -n "$json_files" ]; then
            echo "Found JSON files:"
            echo "$json_files"
            for file in $json_files; do
              echo "Checking $file..."
              jsonlint "$file" -q
              echo "✓ $file"
            done
            echo "✓ JSON linting passed"
          else
            echo "No JSON files found to lint"
          fi

      - name: Lint YAML files
        run: |
          echo "Checking YAML files..."
          yaml_files=$(find . \( -name "*.yml" -o -name "*.yaml" \) \
                             -not -path "./node_modules/*" -not -path "./.bmad-core/*")
          if [ -n "$yaml_files" ]; then
            echo "Found YAML files:"
            echo "$yaml_files"
            yamllint --config-file config/.yamllint.yml $yaml_files
            echo "✓ YAML linting passed"
          else
            echo "No YAML files found to lint"
          fi

      - name: Lint TypeScript/JavaScript files
        run: |
          echo "Checking TypeScript/JavaScript files..."
          if [ -f "package.json" ]; then
            if grep -q '"lint"' package.json; then
              echo "Using pnpm workspace lint script..."
              pnpm install --frozen-lockfile || \
                echo "No lockfile found, installing dependencies..."
              pnpm lint
              echo "✓ TypeScript/JavaScript linting passed"
            else
              echo "No lint script found in package.json - skipping TypeScript/JavaScript linting"
            fi
          else
            echo "No package.json found - skipping TypeScript/JavaScript linting"
          fi

      - name: Summary
        run: |
          echo "All linting checks completed! ✓"
