name: Test Minimal

on:
  push:
    branches: [feature/story-0.6-ci-cd-pipeline-foundation]
  pull_request:
    branches: [main, master, develop]

jobs:
  test:
    name: Minimal Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test basic functionality
        run: |
          echo "Testing basic functionality..."
          ls -la
          echo "Node.js version:"
          node --version
          echo "npm version:"
          npm --version
          echo "Test completed successfully"